export const colors = {
  '$primary-low': '#0ADBE3',
  '$primary-light': '#37B6C4',
  '$primary-mid': '#039BE5',
  '$primary-dark': '#037F9C',
  '$secondary-low': '#D5CCC3',
  '$secondary-light': '#8A817B',
  '$secondary-mid': '#707070',
  '$secondary-dark': '#484440',
  '$background-low': '#F8F9FA',
  '$background-mid': '#F1F1F1',
  $warning: '#FEAC0E',
  '$warning-hover': ' #ED9C2E',
  '$gray-low': ' #EEEEEE',
  '$gray-dark': ' #363636',
  $danger: '#D93025',
  '$danger-hover': ' #952C0C',
  $blue: '#0897E9',
  $success: '#1E8E3E',
  '$success-hover': ' #1D7030',
  $purple: '#6B48FF',
  $black: '#000000',
  $white: '#FFFFFF',
};

export const lightColors = [
  '$secondary-low',
  '$background-low',
  '$background-mid',
  '$gray-low',
  '$white',
  '$warning',
  '$warning-hover',
];
